sam - added recommendation entity, controller, and tests
ucsb-cs156-s22/team02-s22-5pm-3 pull request #42
Opened 2022-04-29 00:10 UTC by TokyoExpress

Created new API endpoint with commands to get, set, update, and delete Recommendation Requests from the added database table.

2022-04-29 06:35 UTC, yuheho7749 commented on src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestsControllerTests.java
> +                                .done(false)
Need better tests

2022-04-29 06:36 UTC, yuheho7749 commented on src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestsControllerTests.java
> +                                .done(false)
Need better tests; fail mutation testing (do not rely on github actions; run mutation testing on local machine!)

2022-04-29 06:37 UTC, yuheho7749 commented on src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestsControllerTests.java
> +                                .build();
Need better tests (fails mutation testing)

2022-04-29 06:39 UTC, yuheho7749 requested changes
Check mutation testing on local machine; do not rely on github actions to run the mutation testing

2022-04-29 06:39 UTC, yuheho7749 commented on src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestsControllerTests.java
> +                                .build();
Need better testing (fails mutation testing)

2022-04-29 06:39 UTC, yuheho7749 commented on src/test/java/edu/ucsb/cs156/example/controllers/RecommendationRequestsControllerTests.java
> +                                .done(false)
Need better tests; fail mutation testing (do not rely on github actions; run mutation testing on local machine!)

2022-04-29 08:30 UTC, TokyoExpress commented
Fixed - mutation now passes locally.

2022-04-29 22:21 UTC, yuheho7749 approved these changes
LGTM
Sam, pls use/update the kanban board and link the corresponding issues that this PR will close (use the menu at the right under "Development" to link the issues)

2022-04-30 01:18 UTC, jwangathan approved these changes
LGTM all tests passed

2022-04-30 01:18 UTC, merged