Added Entity, Repository, Controller, and Tests for UCSB Organization
ucsb-cs156-s22/team02-s22-5pm-3 pull request #43
Opened 2022-04-29 03:17 UTC by jwangathan

Created Entity and Repository class for UCSB Organization. Created Controller and Tests for GET(index), POST(create), GET(show), PUT(edit), and DELETE for UCSB Organization. Closes #22 #23 #24 #25 #26

2022-05-01 21:13 UTC, aaron-sgy requested changes
# Test Issues

Needs better test. 2 mutations survived. 

<img width="1235" alt="Screen Shot 2022-05-01 at 14 07 36" src="https://user-images.githubusercontent.com/97419450/166164680-cac9fa84-aa49-4301-86f8-083b33d56014.png">

<img width="1317" alt="Screen Shot 2022-05-01 at 14 07 24" src="https://user-images.githubusercontent.com/97419450/166164675-6412978a-9c47-4c13-8ee9-bc3294aaf244.png">
.

# API

Api's GET/POST/DELETE/ all work great. However, for PUT, when you edit the orgCode in the incoming block, it will create a whole new entry. I think that might be normal? But not too sure. Need someone else to review this.

2022-05-01 23:00 UTC, yuheho7749 commented
The behavior of put/update generating a new entry is not intended.

The reason being, since the orgCode is the unique id (@Id annotation documentation can be found here <https://docs.oracle.com/javaee/7/api/javax/persistence/Id.html>), changing/setting the orgCode to something different in the controller and then calling the ucsbOrganizationRepository.save() function will create a new entry. Notice that the save function is used in both the post and put functions. In other words, if the Id is not found in the database table, it creates a new entry; if the Id is found, it modifies the entry

2022-05-01 23:07 UTC, yuheho7749 requested changes
Needs to match intended behavior of put/update

2022-05-01 23:07 UTC, yuheho7749 commented on src/main/java/edu/ucsb/cs156/example/controllers/UCSBOrganizationController.java
> +        ucsbOrganization.setInactive(incoming.getInactive());
Needs to be changed to match the intended behavior of updating a database entry. Updating should not generate a new entry

2022-05-02 00:17 UTC, yuheho7749 approved these changes
LGTM

2022-05-02 06:44 UTC, aaron-sgy commented
# Test Coverage

All tests passed. 100% mutation tests coverage.

# API: PUT Issue

Using "PUT": When updating an existing UCSBOrganization's orgCode, it no longer creates a new entry. The orgCode cannot be edited through the PUT request, but in the editing body, it still appears, making it seem like the orgCode is editable. I suggest deleting that as well. 

# TLDR

Can technically merge by ignoring the API issue since the API issue is not a critical issue that violates the intended API behavior. But solving that would improve the Webapp overall.

2022-05-02 06:44 UTC, aaron-sgy approved these changes

2022-05-02 22:19 UTC, merged